-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Cycle exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Pdcaを識別するためのID
-}
id : SelectionSet String Api.Object.Cycle
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| Plan
-}
plan : SelectionSet String Api.Object.Cycle
plan =
    Object.selectionForField "String" "plan" [] Decode.string


{-| Do
-}
do : SelectionSet String Api.Object.Cycle
do =
    Object.selectionForField "String" "do" [] Decode.string


{-| Check
-}
check : SelectionSet String Api.Object.Cycle
check =
    Object.selectionForField "String" "check" [] Decode.string


{-| Act
-}
act : SelectionSet String Api.Object.Cycle
act =
    Object.selectionForField "String" "act" [] Decode.string


{-| Plan
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.Cycle
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| Plan
-}
updateAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.Cycle
updateAt =
    Object.selectionForField "ScalarCodecs.DateTime" "updateAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)
