-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Team exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| チームを識別するためのID
-}
id : SelectionSet String Api.Object.Team
id =
    Object.selectionForField "String" "id" [] Decode.string


{-| チーム名
-}
name : SelectionSet String Api.Object.Team
name =
    Object.selectionForField "String" "name" [] Decode.string


{-| チーム目標
-}
goal : SelectionSet String Api.Object.Team
goal =
    Object.selectionForField "String" "goal" [] Decode.string


{-| チームの共有事項
-}
information : SelectionSet String Api.Object.Team
information =
    Object.selectionForField "String" "information" [] Decode.string


{-| チームの作成日時
-}
createdAt : SelectionSet Api.ScalarCodecs.DateTime Api.Object.Team
createdAt =
    Object.selectionForField "ScalarCodecs.DateTime" "createdAt" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecDateTime |> .decoder)


{-| 監督
-}
manager : SelectionSet decodesTo Api.Object.UserData -> SelectionSet decodesTo Api.Object.Team
manager object_ =
    Object.selectionForCompositeField "manager" [] object_ identity


{-| 選手
-}
playerList : SelectionSet decodesTo Api.Object.UserData -> SelectionSet (List decodesTo) Api.Object.Team
playerList object_ =
    Object.selectionForCompositeField "playerList" [] object_ (identity >> Decode.list)
